services:

  sql-db-service:
    image: sparkplug-analytics
    container_name: sparkplug-analytics
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
