services:
  ml-service:
    image: sparkplug-ml-service
    container_name: sparkplug-ml-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
