services:

  site-station-analytics:
    image: sparkplug-site-station-analytics
    container_name: sparkplug-site-station-analytics
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - FLASK_ENV=production
      - ENV=prod
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
