services:

  site-station-analytics:
    image: sparkplug-site-station-analytics
    container_name: sparkplug-site-station-analytics
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - ENV=prod
    ports:
      - ${PORT}:${PORT}
