services:

  sql-db-service:
    image: sparkplug-station-management-service
    container_name: sparkplug-station-management-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
