services:

  web-dashboard:
    image: sparkplug-web-dashboard
    container_name: sparkplug-web-dashboard
    build:
      context: ./web-dashboard
      target: development
    env_file:
      - ./.env
      - ./web-dashboard/.env
    environment:
      - PORT=${WEB_DASHBOARD_PORT}
    ports:
      - ${WEB_DASHBOARD_PORT}:${WEB_DASHBOARD_PORT}
    develop:
      watch:
        - action: sync
          path: ./web-dashboard
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./web-dashboard/package.json

  user-management:
    image: sparkplug-user-management
    container_name: sparkplug-user-management
    build:
      context: ./user
      target: development
    env_file:
      - ./.env
      - ./user/.env
    environment:
      - PORT=${USER_MAMANGEMENT_PORT}
      - WEB_DOMAIN=${WEB_DASHBOARD_PORT}
    ports:
      - ${USER_MAMANGEMENT_PORT}:${USER_MAMANGEMENT_PORT}
    develop:
      watch:
        - action: sync
          path: ./user
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./user/package.json

  station-site-management:
    image: sparkplug-station-site-management
    container_name: sparkplug-station-site-management
    build:
      context: ./station-sites-management/server
    env_file:
      - ./.env
      - ./station-sites-management/server/.env
    environment:
      - FLASK_ENV=production
      - ENV=prod
      - SERVER_HOST=${STATION_SITE_HOST}
      - SERVER_PORT=${STATION_SITE_PORT}
    ports:
      - ${STATION_SITE_PORT}:${STATION_SITE_PORT}
    develop:
      watch:
        - action: sync
          path: ./station-sites-management/server
          target: /app
        - action: rebuild
          path: ./station-sites-management/server/requirements.txt
