services:
  web-dashboard:
    extends:
      file: compose.prod.yaml
      service: web-dashboard
    restart: "no"
    build:
      target: development
    depends_on:
      - user-management
      - site-station-analytics
      - monitoring
    develop:
      watch:
        - action: sync
          path: ./web-dashboard
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./web-dashboard/package.json

  user-management:
    extends:
      file: compose.prod.yaml
      service: user-management
    restart: "no"
    build:
      target: development
    develop:
      watch:
        - action: sync
          path: ./user-management
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./user-management/package.json

  site-station-analytics:
    extends:
      file: compose.prod.yaml
      service: site-station-analytics
    restart: "no"
    build:
      target: development
    depends_on:
      - user-management
    develop:
      watch:
        - action: sync
          path: ./site-station-analytics
          target: /app
        - action: rebuild
          path: ./site-station-analytics/requirements.txt

  monitoring:
    extends:
      file: compose.prod.yaml
      service: monitoring
    restart: "no"
    build:
      target: development
    depends_on:
      - user-management
      - site-station-analytics
    develop:
      watch:
        - action: sync
          path: ./monitoring
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./monitoring/package.json

  simulator-client:
    extends:
      file: compose.prod.yaml
      service: simulator-client
    restart: "no"
    build:
      target: development
    depends_on:
      - simulator-server
    develop:
      watch:
        - action: sync
          path: ./simulator/client
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./simulator/client/package.json

  simulator-server:
    extends:
      file: compose.prod.yaml
      service: simulator-server
    restart: "no"
    build:
      target: development
    depends_on:
      - monitoring
    develop:
      watch:
        - action: sync
          path: ./simulator/server
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./simulator/server/package.json
