services:
  web-dashboard:
    image: ${CONTAINER_REGISTRY}/web-dashboard
    container_name: sparkplug-web-dashboard
    build:
      context: ./web-dashboard
    ports:
      - ${WEB_DASHBOARD_PORT}:${WEB_DASHBOARD_PORT}
    environment:
      PORT: ${WEB_DASHBOARD_PORT}
      NGINX_PORT: ${WEB_DASHBOARD_PORT}

  user-management:
    image: ${CONTAINER_REGISTRY}/user-management
    container_name: sparkplug-user-management
    build:
      context: ./user-management
    ports:
      - ${USER_PORT}:${USER_PORT}
    environment:
      PORT: ${USER_PORT}

  sql-db-service:
    image: ${CONTAINER_REGISTRY}/sql-db-service
    container_name: sparkplug-sql-db-service
    build:
      context: ./sql-db-service
    ports:
      - ${SQL_SERVICE_PORT}:${SQL_SERVICE_PORT}
    environment:
      PORT: ${SQL_SERVICE_PORT}

  mongo-db-service:
    image: ${CONTAINER_REGISTRY}/mongo-db-service
    container_name: sparkplug-mongo-db-service
    build:
      context: ./mongo-db-service
    ports:
      - ${MONGO_SERVICE_PORT}:${MONGO_SERVICE_PORT}
    environment:
      PORT: ${MONGO_SERVICE_PORT}

  station-management:
    image: ${CONTAINER_REGISTRY}/station-management
    container_name: sparkplug-station-management
    build:
      context: ./station-management
    ports:
      - ${STATION_PORT}:${STATION_PORT}
    environment:
      PORT: ${STATION_PORT}

  analytics:
    image: ${CONTAINER_REGISTRY}/analytics
    container_name: sparkplug-analytics
    build:
      context: ./analytics
    ports:
      - ${ANALYTICS_PORT}:${ANALYTICS_PORT}
    environment:
      PORT: ${ANALYTICS_PORT}

  monitoring:
    image: ${CONTAINER_REGISTRY}/monitoring
    container_name: sparkplug-monitoring
    build:
      context: ./monitoring
    ports:
      - ${MONITORING_PORT}:${MONITORING_PORT}
    environment:
      PORT: ${MONITORING_PORT}

  ml-service:
    image: ${CONTAINER_REGISTRY}/ml-service
    container_name: sparkplug-ml-service
    build:
      context: ./ml-service
    ports:
      - ${AI_SERVICES_PORT}:${AI_SERVICES_PORT}
    environment:
      PORT: ${AI_SERVICES_PORT}

  simulator-client:
    image: ${CONTAINER_REGISTRY}/simulator-client
    container_name: sparkplug-simulator-client
    build:
      context: ./simulator/client
    ports:
      - ${SIMULATOR_CLIENT_PORT}:${SIMULATOR_CLIENT_PORT}
    environment:
      PORT: ${SIMULATOR_CLIENT_PORT}
      NGINX_PORT: ${SIMULATOR_CLIENT_PORT}

  simulator-server:
    image: ${CONTAINER_REGISTRY}/simulator-server
    container_name: sparkplug-simulator-server
    build:
      context: ./simulator/server
    ports:
      - ${SIMULATOR_SERVER_PORT}:${SIMULATOR_SERVER_PORT}
    environment:
      PORT: ${SIMULATOR_SERVER_PORT}
