services:
  web-dashboard:
    extends:
      file: compose.prod.yaml
      service: web-dashboard
    build:
      target: development
    environment:
      VITE_AUTH_API: ${WEB_DASHBOARD_AUTH_API}
      VITE_USER_API: ${WEB_DASHBOARD_USER_API}
      VITE_SITE_API: ${WEB_DASHBOARD_SITE_API}
      VITE_STATION_API: ${WEB_DASHBOARD_STATION_API}
      VITE_STATION_ANALYTICS_API: ${WEB_DASHBOARD_ANALYTICS_STATION_API}
      VITE_STATION_STATUS_API: ${WEB_DASHBOARD_STATION_STATUS_API}
      VITE_STATION_EVENT_API: ${WEB_DASHBOARD_STATION_EVENT_API}
      VITE_STATION_EVENT_WS: ${WEB_DASHBOARD_STATION_EVENT_WS}
      VITE_STATION_PREDICTION_API: ${WEB_DASHBOARD_STATION_PREDICTION_API}
      VITE_STATION_ENERGY_FORECAST_API: ${WEB_DASHBOARD_ENERGY_FORECAST_API}
      VITE_STATION_WAIT_TIME_ESTIMATION_API: ${WEB_DASHBOARD_STATION_WAIT_TIME_ESTIMATION_API}
      VITE_SECURE_LOCAL_STORAGE_PREFIX: ${WEB_DASHBOARD_SECURE_LOCAL_STORAGE_PREFIX}
      VITE_SECURE_LOCAL_STORAGE_HASH_KEY: ${WEB_DASHBOARD_SECURE_LOCAL_STORAGE_HASH_KEY}
    depends_on:
      - user-management
      - station-management
      - monitoring
      - analytics
      - ml-service
    develop:
      watch:
        - action: sync
          path: ./web-dashboard
          target: /app
        - action: rebuild
          path: ./web-dashboard/package.json

  user-management:
    extends:
      file: compose.prod.yaml
      service: user-management
    build:
      target: development
    environment:
      WEB_DOMAIN: ${WEB_DASHBOARD_DOMAIN}
      MYSQL_URI: ${MYSQL_URI}
      JWT_SECRET: ${USER_JWT_SECRET}
    develop:
      watch:
        - action: sync
          path: ./user-management
          target: /app
        - action: rebuild
          path: ./user-management/package.json

  station-management:
    extends:
      file: compose.prod.yaml
      service: station-management
    build:
      target: development
    environment:
      WEB_DOMAINS: ${WEB_DASHBOARD_DOMAIN},${SIMULATOR_CLIENT_DOMAIN}
      AUTH_API_ENDPOINT: ${STATION_AUTH_API_ENDPOINT}
      MYSQL_URI: ${MYSQL_URI}
      GEOIP_ACCOUNT_ID: ${STATION_GEOIP_ACCOUNT_ID}
      GEOIP_LICENSE_KEY: ${STATION_GEOIP_LICENSE_KEY}
    depends_on:
      - user-management
    develop:
      watch:
        - action: sync
          path: ./station-management
          target: /app
        - action: rebuild
          path: ./station-management/requirements.txt

  monitoring:
    extends:
      file: compose.prod.yaml
      service: monitoring
    build:
      target: development
    environment:
      WEB_DOMAIN: ${WEB_DASHBOARD_DOMAIN}
      AUTH_API_ENDPOINT: ${MONITORING_AUTH_API_ENDPOINT}
      STATION_API_ENDPOINT: ${MONITORING_STATION_API_ENDPOINT}
      MYSQL_URI: ${MYSQL_URI}
      MONGODB_URI: ${MONGODB_URI}
    depends_on:
      - user-management
      - station-management
    develop:
      watch:
        - action: sync
          path: ./monitoring
          target: /app
        - action: rebuild
          path: ./monitoring/package.json

  analytics:
    extends:
      file: compose.prod.yaml
      service: analytics
    build:
      target: development
    environment:
      WEB_DOMAIN: ${WEB_DASHBOARD_DOMAIN}
      AUTH_API_ENDPOINT: ${ANALYTICS_AUTH_API_ENDPOINT}
      MYSQL_URI: ${MYSQL_URI}
      MONGODB_URI: ${MONGODB_URI}
      ENERGY_FORECAST_MODEL_PATH: ${ANALYTICS_ENERGY_FORECAST_MODEL_PATH}
    depends_on:
      - user-management
    develop:
      watch:
        - action: sync
          path: ./analytics
          target: /app
        - action: rebuild
          path: ./analytics/requirements.txt

  ml-service:
    extends:
      file: compose.prod.yaml
      service: ml-service
    build:
      target: development
    environment:
      WEB_DOMAIN: ${WEB_DASHBOARD_DOMAIN}
      AUTH_API_ENDPOINT: ${ML_SERVICE_AUTH_API_ENDPOINT}
      STATION_API_ENDPOINT: ${ML_SERVICE_STATION_API_ENDPOINT}
      MONGODB_URI: ${MONGODB_URI}
      STATION_PREDICTION_MODEL_PATH: ${ML_SERVICE_STATION_PREDICTION_MODEL_PATH}
      WAIT_TIME_MODEL_PATH: ${ML_SERVICE_WAIT_TIME_PREDICTION_MODEL_PATH}
    depends_on:
      - user-management
      - station-management
    develop:
      watch:
        - action: sync
          path: ./ml-service
          target: /app
        - action: rebuild
          path: ./ml-service/requirements.txt

  simulator-client:
    extends:
      file: compose.prod.yaml
      service: simulator-client
    build:
      target: development
    environment:
      REACT_APP_WS_ENDPOINT: ${SIMULATOR_CLIENT_SERVER_WS}
      REACT_APP_STATION_API_ENDPOINT: ${SIMULATOR_CLIENT_STATION_API_ENDPOINT}
    depends_on:
      - simulator-server
      - station-management
    develop:
      watch:
        - action: sync
          path: ./simulator/client
          target: /app
        - action: rebuild
          path: ./simulator/client/package.json

  simulator-server:
    extends:
      file: compose.prod.yaml
      service: simulator-server
    build:
      target: development
    environment:
      WEB_DOMAIN: ${SIMULATOR_CLIENT_DOMAIN}
      STATION_API_ENDPOINT: ${SIMULATOR_SERVER_STATION_API_ENDPOINT}
      CSMS_WS_ENDPOINT: ${SIMULATOR_CSMS_WS}
    depends_on:
      - station-management
      - monitoring
    develop:
      watch:
        - action: sync
          path: ./simulator/server
          target: /app
        - action: rebuild
          path: ./simulator/server/package.json
