services:
  web-dashboard:
    image: ${CONTAINER_REGISTRY}/web-dashboard
    container_name: sparkplug-web-dashboard
    build:
      context: ./web-dashboard
    ports:
      - ${WEB_DASHBOARD_PORT}:${WEB_DASHBOARD_PORT}
    environment:
      PORT: ${WEB_DASHBOARD_PORT}
      NGINX_PORT: ${WEB_DASHBOARD_PORT}

  user-management:
    image: ${CONTAINER_REGISTRY}/user-management
    container_name: sparkplug-user-management
    build:
      context: ./user-management
    ports:
      - ${USER_PORT}:${USER_PORT}
    environment:
      PORT: ${USER_PORT}

  site-station-analytics:
    image: ${CONTAINER_REGISTRY}/site-station-analytics
    container_name: sparkplug-site-station-analytics
    build:
      context: ./site-station-analytics
    ports:
      - ${STATION_PORT}:${STATION_PORT}
    environment:
      PORT: ${STATION_PORT}

  monitoring:
    image: ${CONTAINER_REGISTRY}/monitoring
    container_name: sparkplug-monitoring
    build:
      context: ./monitoring
    ports:
      - ${MONITORING_PORT}:${MONITORING_PORT}
    environment:
      PORT: ${MONITORING_PORT}

  simulator-client:
    image: ${CONTAINER_REGISTRY}/simulator-client
    container_name: sparkplug-simulator-client
    build:
      context: ./simulator/client
    ports:
      - ${SIMULATOR_CLIENT_PORT}:${SIMULATOR_CLIENT_PORT}
    environment:
      PORT: ${SIMULATOR_CLIENT_PORT}
      NGINX_PORT: ${SIMULATOR_CLIENT_PORT}

  simulator-server:
    image: ${CONTAINER_REGISTRY}/simulator-server
    container_name: sparkplug-simulator-server
    build:
      context: ./simulator/server
    ports:
      - ${SIMULATOR_SERVER_PORT}:${SIMULATOR_SERVER_PORT}
    environment:
      PORT: ${SIMULATOR_SERVER_PORT}
  
  sql-db-service:
    image: ${CONTAINER_REGISTRY}/sql-db-service
    container_name: sparkplug-sql-db-service
    build:
      context: ./sql-db-service
    ports:
      - ${SQL_SERVICE_PORT}:${SQL_SERVICE_PORT}
    environment:
      PORT: ${SQL_SERVICE_PORT}

  mongo-db-service:
    image: ${CONTAINER_REGISTRY}/mongo-db-service
    container_name: sparkplug-mongo-db-service
    build:
      context: ./mongo-db-service
    ports:
      - ${MONGO_SERVICE_PORT}:${MONGO_SERVICE_PORT}
    environment:
      PORT: ${MONGO_SERVICE_PORT}

  station-management-service:
    image: ${CONTAINER_REGISTRY}/station-management-service
    container_name: sparkplug-station-management-service
    build:
      context: ./station-management-service
    ports:
      - ${STATION_MANAGEMENT_PORT}:${STATION_MANAGEMENT_PORT}
    environment:
      PORT: ${STATION_MANAGEMENT_PORT}
  
  station-analytics-service:
    image: ${CONTAINER_REGISTRY}/station-analytics-service
    container_name: sparkplug-station-analytics-service
    build:
      context: ./station-analytics-service
    ports:
      - ${STATION_ANALYTICS_PORT}:${STATION_ANALYTICS_PORT}
    environment:
      PORT: ${STATION_ANALYTICS_PORT}