services:
  web-dashboard:
    image: ${CONTAINER_REGISTRY}/web-dashboard
    container_name: sparkplug-web-dashboard
    build:
      context: ./web-dashboard
    ports:
      - ${WEB_DASHBOARD_PORT}:${WEB_DASHBOARD_PORT}
    environment:
      PORT: ${WEB_DASHBOARD_PORT}
      NGINX_PORT: ${WEB_DASHBOARD_PORT}

  user-management:
    image: ${CONTAINER_REGISTRY}/user-management
    container_name: sparkplug-user-management
    build:
      context: ./user-management
    ports:
      - ${USER_PORT}:${USER_PORT}
    environment:
      PORT: ${USER_PORT}

  site-station-analytics:
    image: ${CONTAINER_REGISTRY}/site-station-analytics
    container_name: sparkplug-site-station-analytics
    build:
      context: ./site-station-analytics
    ports:
      - ${STATION_PORT}:${STATION_PORT}
    environment:
      PORT: ${STATION_PORT}

  monitoring:
    image: ${CONTAINER_REGISTRY}/monitoring
    container_name: sparkplug-monitoring
    build:
      context: ./monitoring
    ports:
      - ${MONITORING_PORT}:${MONITORING_PORT}
    environment:
      PORT: ${MONITORING_PORT}

  simulator-client:
    image: ${CONTAINER_REGISTRY}/simulator-client
    container_name: sparkplug-simulator-client
    build:
      context: ./simulator/client
    ports:
      - ${SIMULATOR_CLIENT_PORT}:${SIMULATOR_CLIENT_PORT}
    environment:
      PORT: ${SIMULATOR_CLIENT_PORT}
      NGINX_PORT: ${SIMULATOR_CLIENT_PORT}

  simulator-server:
    image: ${CONTAINER_REGISTRY}/simulator-server
    container_name: sparkplug-simulator-server
    build:
      context: ./simulator/server
    ports:
      - ${SIMULATOR_SERVER_PORT}:${SIMULATOR_SERVER_PORT}
    environment:
      PORT: ${SIMULATOR_SERVER_PORT}
