services:
  web-dashboard:
    extends:
      file: compose.prod.yaml
      service: web-dashboard
    build:
      target: development
    environment:
      REACT_APP_AUTH_API_ENDPOINT: ${WEB_DASHBOARD_AUTH_API}
      REACT_APP_USER_API_ENDPOINT: ${WEB_DASHBOARD_USER_API}
      REACT_APP_SITE_API_ENDPOINT: ${WEB_DASHBOARD_SITE_API}
      REACT_APP_STATION_API_ENDPOINT: ${WEB_DASHBOARD_STATION_API}
      REACT_APP_ANALYTICS_SITE_API_ENDPOINT: ${WEB_DASHBOARD_ANALYTICS_SITE_API}
      REACT_APP_ANALYTICS_STATION_API_ENDPOINT: ${WEB_DASHBOARD_ANALYTICS_STATION_API}
      REACT_APP_MONITORING_API_ENDPOINT: ${WEB_DASHBOARD_MONITORING_API}
      REACT_APP_MONITORING_WS_ENDPOINT: ${WEB_DASHBOARD_MONITORING_WS}
      REACT_APP_SECURE_LOCAL_STORAGE_PREFIX: ${WEB_DASHBOARD_SECURE_LOCAL_STORAGE_PREFIX}
      REACT_APP_SECURE_LOCAL_STORAGE_HASH_KEY: ${WEB_DASHBOARD_SECURE_LOCAL_STORAGE_HASH_KEY}
    depends_on:
      - user-management
      - site-station-analytics
      - monitoring
    develop:
      watch:
        - action: sync
          path: ./web-dashboard
          target: /app
        - action: rebuild
          path: ./web-dashboard/package.json

  user-management:
    extends:
      file: compose.prod.yaml
      service: user-management
    build:
      target: development
    environment:
      WEB_DOMAIN: ${WEB_DASHBOARD_DOMAIN}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      JWT_SECRET: ${USER_JWT_SECRET}
    develop:
      watch:
        - action: sync
          path: ./user-management
          target: /app
        - action: rebuild
          path: ./user-management/package.json

  site-station-analytics:
    extends:
      file: compose.prod.yaml
      service: site-station-analytics
    build:
      target: development
    environment:
      WEB_DOMAIN: ${WEB_DASHBOARD_DOMAIN}
      AUTH_API_ENDPOINT: ${STATION_AUTH_API_ENDPOINT}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MONGODB_URL: ${MONGODB_URL}
    depends_on:
      - user-management
    develop:
      watch:
        - action: sync
          path: ./site-station-analytics
          target: /app
        - action: rebuild
          path: ./site-station-analytics/requirements.txt

  monitoring:
    extends:
      file: compose.prod.yaml
      service: monitoring
    build:
      target: development
    environment:
      WEB_DOMAIN: ${WEB_DASHBOARD_DOMAIN}
      AUTH_API_ENDPOINT: ${MONITORING_AUTH_API_ENDPOINT}
      STATION_API_ENDPOINT: ${MONITORING_STATION_API_ENDPOINT}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MONGODB_URL: ${MONGODB_URL}
    depends_on:
      - user-management
      - site-station-analytics
    develop:
      watch:
        - action: sync
          path: ./monitoring
          target: /app
        - action: rebuild
          path: ./monitoring/package.json

  simulator-client:
    extends:
      file: compose.prod.yaml
      service: simulator-client
    build:
      target: development
    environment:
      REACT_APP_WS_ENDPOINT: ${SIMULATOR_CLIENT_SERVER_WS}
      REACT_APP_STATION_IDENTITY: ${SIMULATOR_STATION_IDENTITY}
    depends_on:
      - simulator-server
    develop:
      watch:
        - action: sync
          path: ./simulator/client
          target: /app
        - action: rebuild
          path: ./simulator/client/package.json

  simulator-server:
    extends:
      file: compose.prod.yaml
      service: simulator-server
    build:
      target: development
    environment:
      WEB_DOMAIN: ${SIMULATOR_CLIENT_DOMAIN}
      CSMS_WS_ENDPOINT: ${SIMULATOR_CSMS_WS}
      STATION_IDENTITY: ${SIMULATOR_STATION_IDENTITY}
      STATION_PASSWORD: ${SIMULATOR_STATION_PASSWORD}
      STATION_CONFIGURATION: ${SIMULATOR_STATION_CONFIGURATION}
    depends_on:
      - monitoring
    develop:
      watch:
        - action: sync
          path: ./simulator/server
          target: /app
        - action: rebuild
          path: ./simulator/server/package.json

  sql-db-service:
    extends:
      file: compose.prod.yaml
      service: sql-db-service
    build:
      target: development
    environment:
      WEB_DOMAIN: ${WEB_DASHBOARD_DOMAIN}
      AUTH_API_ENDPOINT: ${STATION_AUTH_API_ENDPOINT}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    develop:
      watch:
        - action: sync
          path: ./sql-db-service
          target: /app
        - action: rebuild
          path: ./sql-db-service/package.json
  
  mongo-db-service:
    extends:
      file: compose.prod.yaml
      service: mongo-db-service
    build:
      target: development
    environment:
      MONGODB_URL: ${MONGODB_URL}
    develop:
      watch:
        - action: sync
          path: ./mongo-db-service
          target: /app
        - action: rebuild
          path: ./mongo-db-service/package.json

  station-management-service:
    extends:
      file: compose.prod.yaml
      service: station-management-service
    build:
      target: development
    environment:
      WEB_DOMAIN: ${WEB_DASHBOARD_DOMAIN}
      AUTH_API_ENDPOINT: ${STATION_AUTH_API_ENDPOINT}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MONGODB_URL: ${MONGODB_URL}
    depends_on:
      - user-management
      - site-station-analytics
      - monitoring
    develop:
      watch:
        - action: sync
          path: ./station-management-service
          target: /app
        - action: rebuild
          path: ./station-management-service/package.json 

  station-analytics-service:
    extends:
      file: compose.prod.yaml
      service: station-analytics-service
    build:
      target: development
    environment:
      WEB_DOMAIN: ${WEB_DASHBOARD_DOMAIN}
      AUTH_API_ENDPOINT: ${STATION_AUTH_API_ENDPOINT}
    depends_on:
      - user-management
      - site-station-analytics
      - monitoring
    develop:
      watch:
        - action: sync
          path: ./station-analytics-service
          target: /app
        - action: rebuild
          path: ./station-analytics-service/package.json