services:
  simulator-client:
    image: sparkplug-simulator-client
    container_name: sparkplug-simulator-client
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
