services:
  station-management:
    image: sparkplug-station-management
    container_name: sparkplug-station-management
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - ${PORT}:${PORT}
